### ISSUE TITLE
One file can't decompile

### ISSUE THREAD

**Issue by bbday** [wibiti/evedec#5]
There is this error with just one file, when try to decompile, from 2 eve update ago:

Can't decompile \eve-16.05.1346598\prometheus_client\parser.py

**Comment by regner** [comment]
I mean, you could just skip it. Its literally just https://github.com/prometheus/client_python/tree/master/prometheus_client.

**Comment by wibiti** [comment]
Thanks. I'll take a look when I have time, maybe next week.

On Jul 10, 2018 7:17 AM, "bbday" <notifications@github.com> wrote:

There is this error with just one file, when try to decompile, from 2 eve
update ago:

Can't decompile \eve-16.05.1346598\prometheus_client\parser.py

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wibiti/evedec/issues/5>, or mute the thread

**Comment by wibiti** [comment]
I just put a fix for this in uncompyle2.
